version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
  auth:
    image: theykk.com/ykk/auth
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env.docker
    healthcheck:
      test: [ "CMD", "curl", "-f" ,"http://localhost:8080/ready" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    depends_on:
      - redis
      - postgres

volumes:
  postgres-db-volume: